
image:
  - Visual Studio 2017

platform:
  - x86
  - x64
  #- Any CPU

# set CURRENT_DATE_TIME=%date:~0,4%-%date:~5,2%-%date:~8,2%

build_script:
  - cmd: echo "build_script"

for:
-
  matrix:
    only:
      #- platform: x86
      - platform: x64
      #- platform: Any CPU

  test_script:
    - cmd: echo "test_script"
    - cmd: set
    - cmd: set packagename=%APPVEYOR_REPO_TAG_NAME%-windows-x64-%date:~10,4%%date:~7,2%%date:~4,2%.7z
    - cmd: |
      if %APPVEYOR_REPO_TAG% == "true" (
        echo "APPVEYOR_REPO_TAG = true"
      ) else (
        echo "APPVEYOR_REPO_TAG = false";
      )
    # - cmd: 7z a -t7z %APPVEYOR_REPO_TAG_NAME%-windows-x64-%date:~10,4%%date:~7,2%%date:~4,2%.7z main.c
    - ps: |
        if ($env:APPVEYOR_REPO_TAG -eq "true")
        {
            echo "APPVEYOR_REPO_TAG is true";
        }
        else
        {
            echo "APPVEYOR_REPO_TAG is false";
        }

    - ps: |
        if ($env:APPVEYOR_REPO_TAG -eq "false")
        {
            echo "APPVEYOR_REPO_TAG is false ------";
            echo $env:APPVEYOR_REPO_TAG;
            echo $env:packagename;
            echo "-----";
            echo $APPVEYOR_REPO_TAG;
            echo $packagename;
            echo %packagename%;
        }
    # - ps: |
    #   if ($APPVEYOR_REPO_TAG == false)
    #   {
    #     echo "APPVEYOR_REPO_TAG is true"
    #   }

before_deploy:
  - cmd: echo "before_deploy"
  - cmd: ls

artifacts:
  - path: '*.7z'

deploy:
  provider: GitHub
  artifacts:
  auth_token:
    secure: Ydv3jxxAP6HvexomaFRj4cXpoUomi/NfumB/eWeGW2Qt/qA7xLdq+EXeQpdpVfi+
  draft: false
  prerelease: false
  on:
    # branch: master
    platform: x64
    APPVEYOR_REPO_TAG: true

