
image:
  - Visual Studio 2017

platform:
  # - x86
  - x64
  #- Any CPU

build_script:
  - cmd: echo "build_script"
  - cmd: 7z a main.zip main.c

for:
-
  matrix:
    only:
      #- platform: x86
      - platform: x64
      #- platform: Any CPU

  test_script:
    - cmd: echo "test_script"

before_deploy:
  - cmd: echo "before_deploy"
  - cmd: ls

deploy:
  provider: GitHub
  artifact: /.*\.zip/           # upload all NuGet packages to release assets
  auth_token:
    secure: mkCzk5/XVb78Atxs5I4lthSLaGSifr7hv1NiRQpsD45BWQsoY5BAhWUpVQRCASP/
  draft: false
  prerelease: false
  on:
    # branch: master
    APPVEYOR_REPO_TAG: true

