
image:
  - Visual Studio 2017

platform:
  - x86
  - x64
  #- Any CPU

build_script:
  - cmd: gcc main.c

for:
-
  matrix:
    only:
      #- platform: x86
      - platform: x64
      #- platform: Any CPU

  test_script:
    - cmd: echo "test_script"

before_deploy:
  - cmd: echo "before_deploy"
  - cmd: ls

deploy:
  provider: GitHub
  artifact: /.*\.out/           # upload all NuGet packages to release assets
  auth_token:
    secure: QZNfFHSeBHg/QSjPRBsKydwqZnwXik9thbRWOJZeBw2PjYPux94SyCwTKL/NH0MB
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: false

