
image:
  - Visual Studio 2017

platform:
  - x86
  - x64
  #- Any CPU

# set CURRENT_DATE_TIME=%date:~0,4%-%date:~5,2%-%date:~8,2%

build_script:
  - set CURRENT_DATE_TIME=%date:~10,4%-%date:~7,2%-%date:~4,2%
  - cmd: echo ${APPVEYOR_REPO_TAG_NAME}
  - cmd: echo %APPVEYOR_REPO_TAG_NAME%
  - cmd: echo %CURRENT_DATE_TIME%
  - cmd: echo "build_script"
  - cmd: 7z a -t7z ${APPVEYOR_REPO_TAG_NAME}-windows-x64-%CURRENT_DATE_TIME%.7z main.c

for:
-
  matrix:
    only:
      #- platform: x86
      - platform: x64
      #- platform: Any CPU

  test_script:
    - cmd: echo "test_script"

before_deploy:
  - cmd: echo "before_deploy"
  - cmd: ls

artifacts:
  - path: main.zip

deploy:
  provider: GitHub
  artifacts:
  auth_token:
    secure: Ydv3jxxAP6HvexomaFRj4cXpoUomi/NfumB/eWeGW2Qt/qA7xLdq+EXeQpdpVfi+
  draft: false
  prerelease: false
  on:
    # branch: master
    platform: x64
    APPVEYOR_REPO_TAG: true

