
image:
  - Visual Studio 2017

platform:
  - x86
  - x64
  #- Any CPU

# set CURRENT_DATE_TIME=%date:~0,4%-%date:~5,2%-%date:~8,2%

build_script:
  - cmd: echo "build_script"

for:
-
  matrix:
    only:
      #- platform: x86
      - platform: x64
      #- platform: Any CPU

  test_script:
    - cmd: echo "test_script"

before_deploy:
  - cmd: echo "before_deploy"
  - cmd: ls
  - cmd: 7z a -t7z %APPVEYOR_REPO_TAG_NAME%-windows-x64-%date:~10,4%%date:~7,2%%date:~4,2%.7z main.c

artifacts:
  - path: main.zip

deploy:
  provider: GitHub
  artifacts:
  auth_token:
    secure: Ydv3jxxAP6HvexomaFRj4cXpoUomi/NfumB/eWeGW2Qt/qA7xLdq+EXeQpdpVfi+
  draft: false
  prerelease: false
  on:
    # branch: master
    platform: x64
    APPVEYOR_REPO_TAG: true

