language: c

stages:
  - name: after_success
    if: env(RUN_TEST) IS present

before_install:
  - export BUILD_TYPE=Release
  - export TEST=OK
  - echo  "BUILD_TYPE" $BUILD_TYPE;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install ruby-dev;
      ulimit -c unlimited;
      ulimit -c;
    else
      ulimit -c unlimited;
      ulimit -c;
      sudo sysctl kern.corefile=/cores/core;
    fi

before_script:
  - echo "script ***************"
  - pwd

matrix:
  include:
    - os: osx
      sudo: required
      env: BUILD_ENV=darwin_x64 RUN_TEST=ON
      if: BUILD_VER IS present

    - sudo: required
      env: BUILD_TYPE=Release BUILD_ENV=linux_x64
      
    - sudo: required
      env: BUILD_TYPE=Release RUN_TEST=ON

script:
  - gcc main.c
  - ls -l
  #- if [[ -f core* ]]; then
  - if [[ "$RUN_TEST" != "" ]]; then
      pwd;
      ./a.out;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install gdb;
      echo "crash";
      echo bt | gdb ./a.out core;
    else
      echo bt | lldb -c /cores/core;
    fi;

after_success:
  - echo "after_success"
  - ./a.out

  
deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: $BUILD_ENV*.tar.gz
  skip_cleanup: true
  on:
    tags: true

# notifications:
#  email:
#    recipients:
#    - raozhiming@msn.com
#     on_success: always
#     on_failure: always
