
# language: python
# python: 3.7
sudo: true


matrix:
  include:
  # - env: pythonv=2.7
  - language: android
    dist: trusty
    python: 3.7
    env: pythonv=3.7
    # android:
    #   components:
    #     - tools
    #     - platform-tools
    #     - build-tools-28.0.3
    #     - android-28
    #   licenses:
    #     - 'android-sdk-preview-license-.+'
    #     - 'android-sdk-license-.+'
    #     - 'google-gdk-license-.+'
    addons:
      apt:
        sources:
          - deadsnakes # source required so it finds the package definition below
        packages:
          - python3.7

before_install:
  - pyenv global 3.6
#   - sudo apt-get update
#   - sudo apt-get install python3

install:
  - sudo apt-get -y install python3-pip
  - pip3 install --user virtualenv
  # - pip3 install --upgrade pip
  - python --version
  - python3 --version
  - ls -l /opt/py*
  - ls -l /usr/bin/p*
  - sudo rm /usr/bin/python
  - ln -s /usr/bin/python3.7 /usr/bin/python
  - python --version

script:
  - echo "script"

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

