
# language: python
# python: 3.7
sudo: true


matrix:
  include:
  # - env: pythonv=2.7
  #   install:
  #     - pip -V
  - language: android
    dist: trusty
    python: 3.7
    env: pythonv=3.7

before_install:
  # - sudo apt-get update
  # - sudo apt purge python2.7-minimal
  # - sudo apt-get install python3-pip python3-setuptools
  # - pip3 install --upgrade pip

install:
  # - python3 -m ensurepip --upgrade
  # - python --version
  # - python3 --version
  # - pip3 install --upgrade pip
  # - ls -l /opt/python/
  #- ls -l /usr/bin/p*
  #- sudo rm /usr/bin/python
  #- sudo ln -s /usr/bin/python3.7 /usr/bin/python
  #- sudo rm /usr/bin/python3
  #- sudo ln -s /usr/bin/python3.7 /usr/bin/python3
  #- python --version
  # - python3 -m ensurepip --upgrade
  # - pip3 -V
  - export
  - WEEK_DAY=$(date +%w)
  - echo $WEEK_DAY

script:
  - echo "script"

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

