language: c

before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ruby-dev; fi
  #- if [[ "$TRAVIS_TAG" == "" ]]; then
  - if [[ "$BUILD_ENV" != "" ]]; then
      export BUILD_TYPE=Release; 
      export TEST=OK;
      echo  "BUILD_TYPE" $BUILD_TYPE;
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install ruby-dev; 
      fi
    else 
      export BUILD_TYPE=Debug;
      export BUILD_ENV=test;
    fi

before_script:
  - echo "script ***************"
  - pwd

matrix:
  include:
    - os: osx
      env: BUILD_ENV=darwin_x64
      if: BUILD_VER IS present

    - sudo: required
      env: BUILD_TYPE=Release BUILD_ENV=linux_x64
      
    - sudo: required
      env: BUILD_TYPE=Release RUN_TEST=ON

script:
  - gcc main.c
  - ./a.out
  - ls -l
  #- if [[ -f core* ]]; then
  - if [[ "$TRAVIS_OS_NAME" != "" ]]; then
      pwd;
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install gdb;
      else
        brew install gdb
      fi;
      echo "crash";
      echo bt | gdb ./a.out core*;
    fi

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: $BUILD_ENV*.tar.gz
  skip_cleanup: true
  on:
    tags: true

# notifications:
#  email:
#    recipients:
#    - raozhiming@msn.com
#     on_success: always
#     on_failure: always
