language: c

matrix:
  include:
    - sudo: required
      env: BUILD_TYPE=Release RUN_TEST=ON DEPLOY=TRUE
      if: NOT tag IS present OR tag !~ /^(daily)/

script:
  - echo "script"
  - tar -czf test-$(date +'%Y%m%d%H%M%S').tar.gz test
  - ret=`.ci_scripts/checkCommit.sh`
  - echo "ret is" $ret
  # - if [[ "$TRAVIS_EVENT_TYPE" == "cron" && "$TRAVIS_BRANCH" == "master" && "$DEPLOY" != "" ]]; then
  - if [[ "$TRAVIS_BRANCH" == "deploy" && "$DEPLOY" != "" ]]; then
      .ci_scripts/checkCommit.sh;
      ret=$?;
      echo "ret:"$ret;
      if [[ "$ret" -ne 1 ]]; then
        echo "no commit, do not upload apk!";
        DEPLOY="";
      fi;
    else
      DEPLOY="";
    fi

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "raozhiming"
      - git config --local user.email "raozhiming@elastos.org"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: test*.tar.gz
  skip_cleanup: true
  prerelease: true
  condition: $DEPLOY != ""
  on:
    branch: deploy
  #   tags: false

