language: c

before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ruby-dev; fi
  #- if [[ "$TRAVIS_TAG" == "" ]]; then
  - if [[ "$BUILD_ENV" != "" ]]; then
      export BUILD_TYPE=Release; 
      export TEST=OK;
      echo  "BUILD_TYPE" $BUILD_TYPE;
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install ruby-dev; 
      fi
    else 
      export BUILD_TYPE=Debug;
      export BUILD_ENV=test;
    fi

before_script:
  - echo "script ***************"
  - pwd

matrix:
  include:
    - os: osx
      env: BUILD_ENV=darwin_x64
      if: BUILD_VER IS present

    - os: osx
      env: BUILD_ENV=darwin_x32
      if: NOT BUILD_VER IS present

    - sudo: required
      env: BUILD_TYPE=Debug BUILD_ENV=linux_x64

    - sudo: required
      env: BUILD_TYPE=Release BUILD_ENV=linux_x64
      
    - sudo: required
      env: BUILD_TYPE=Release RUN_TEST=ON

script:
  - if [[ "$BUILD_TYPE" == "Release" ]]; then 
      echo "release ++++++++++++";
    else 
      echo "debug -----------";
    fi
  - mkdir $BUILD_ENV-$BUILD_TYPE
  - pwd
  - ls -l
  - gcc main.c && ./a.out && echo "TRAVIS_TAG" $TRAVIS_TAG
  - echo "BUILD_VER " $BUILD_VER
  - sudo tar -czf $BUILD_ENV-$(date +'%Y%m%d').tar.gz main.c
  - if [[ "$RUN_TEST" != "" ]]; then
      cd .;
      export LD_LIBRARY_PATH=../lib;
      pwd;
      ./a.out --robot -c ../etc/carrier/tests.conf & ;
      ./a.out --cases -c ../etc/carrier/tests.conf -r 3;
    fi

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: $BUILD_ENV*.tar.gz
  skip_cleanup: true
  on:
    tags: true

# notifications:
#  email:
#    recipients:
#    - raozhiming@msn.com
#     on_success: always
#     on_failure: always
