language: node_js
python: 3.7


matrix:
  include:
  - env: pythonv=2.7
  - env: pythonv=3.7
    language:
      - python
      - android
    python: 3.7

install:
  - python --version

script:
  - echo "script"

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

