language: c

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ruby-dev; fi

matrix:
  include:
  - sudo: required
    language: python
    python: 2.7.15
    env: linux
    script:
      - python --version

  - language: python
    sudo: required
    python: 3.6
    env: python
    script:
      - gcc main.c && ./a.out && echo "TRAVIS_TAG" $TRAVIS_TAG
      - python --version

  # - sudo: required
  #   env: linux_64
  #   script:
  #     - gcc main.c && ./a.out && echo "TRAVIS_TAG" $TRAVIS_TAG
  #     - ls /usr -l
  #     - ls /usr/lib32 -l
  #     - ls /usr/libx32 -l
  #   deploy:
  #     provider: releases
  #     api_key: $token
  #     file: a.out
  #     skip_cleanup: true
  #     on:
  #       tags: true
  #       branches:
  #         only:
  #           - master

  # - sudo: required
  #   env: test2
  #   script: gcc main.c && ./a.out
  #   deploy:
  #     provider: releases
  #     api_key: $token
  #     file: main.c
  #     skip_cleanup: true
  #     on:
  #       tags: true
  #       branches:
  #         only:
  #           - master


#  - os: osx
#    script: gcc main.c

# notifications:
#  email:
#    recipients:
#    - raozhiming@msn.com
#     on_success: always
#     on_failure: always
