language: python
python: 3.7


matrix:
  include:
  - env: pythonv=2.7
  - language: android
    python: 3.7
    env: pythonv=3.7
    android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-28
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
    addons:
      apt:
        sources:
          - deadsnakes # source required so it finds the package definition below
        packages:
          - python3.7

# before_install:
#   - sudo apt-get update
#   - sudo apt-get install python3

install:
  - python --version

script:
  - echo "script"

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

