language: c

matrix:
  include:
    - sudo: required
      env: TYPE=TEST RUN_TEST=ON DEPLOY=TRUE
      if: NOT tag IS present OR tag !~ /^(daily)/

    - sudo: required
      env: TYPE=DAILY DEPLOY=TRUE
      if: NOT tag IS present OR tag !~ /^(daily)/

script:
  - echo "script"
  - if [[ "$TYPE" == "TEST" ]]; then
      tar -czf test-$(date +'%Y%m%d%H%M%S').tar.gz test;
    else
      tar -czf daily-$(date +'%Y%m%d%H%M%S').tar.gz test;
    fi
  # - ret=`.ci_scripts/checkCommit.sh`
  # - echo "ret is" $ret
  # - if [[ "$TRAVIS_EVENT_TYPE" == "cron" && "$TRAVIS_BRANCH" == "master" && "$DEPLOY" != "" ]]; then
  # - if [[ "$TRAVIS_BRANCH" == "deploy" && "$DEPLOY" != "" ]]; then
  #     .ci_scripts/checkCommit.sh;
  #     ret=$?;
  #     echo "ret:"$ret;
  #     if [[ "$ret" -ne 1 ]]; then
  #       echo "no commit, do not upload apk!";
  #       DEPLOY="";
  #     fi;
  #   else
  #     DEPLOY="";
  #   fi
  - export WEEK_DAY=$(date +%w)
  - if [[ $WEEK_DAY -eq 2 || $WEEK_DAY -eq 5 ]];then
      echo "ok let's upload";
    fi
  - ls -l
  # - export

before_deploy:
      # Set up git user name and tag this commit
      # - export
      - git config --local user.name "raozhiming"
      - git config --local user.email "raozhiming@elastos.org"
      - export TRAVIS_TAG=$TYPE-$(date +'%Y%m%d%H')-$(git log --format=%h -1)
      - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file:
    - test*.tar.gz
    - daily*.tar.gz
  skip_cleanup: true
  prerelease: true
  on:
    condition: $DEPLOY != ""
    branch: deploy
  #   tags: false

