language: node_js
python: 3.7


matrix:
  include:
  - env: pythonv=2.7
  - language:
      - android
      - python: 3.7
    # python: 3.7
    dist: trusty
    env: pythonv=3.7


install:
  - python --version

script:
  - echo "script"

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

