language: c

matrix:
  include:
    - sudo: required
      env: BUILD_TYPE=Release RUN_TEST=ON

script:
  - echo "script"
  - tar -czf test.tar.gz test

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "raozhiming"
      - git config --local user.email "raozhiming@elastos.org"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: test*.tar.gz
  skip_cleanup: true
  draft: true
  on:
    branch: deploy
  #   tags: false

# notifications:
#  email:
#    recipients:
#    - raozhiming@msn.com
#     on_success: always
#     on_failure: always
