language: c

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ruby-dev; fi

matrix:
  include:
  - sudo: required
    env: ARCHITECTURE_32BIT="True"
    script: gcc main.c && ./a.out
    deploy:
      provider: releases
      api_key: $token
      file: a.out
      skip_cleanup: true
      on:
        tags: false

- sudo: required
    env: test2
    script: gcc main.c && ./a.out
    deploy:
      provider: releases
      api_key: $token
      file: main.c
      skip_cleanup: true
      on:
        tags: false

#  - os: osx
#    script: gcc main.c

#notifications:
#  email:
#    recipients:
#    - raozhiming@msn.com
    #on_success: always
    #on_failure: always
