language: c

stages:
  - name: after_success
    if: env(RUN_TEST) IS present

matrix:
  include:
    - os: osx
      sudo: required
      env: BUILD_ENV=darwin_x64 RUN_TEST=ON
      if: BUILD_VER IS present

    - sudo: required
      env: BUILD_TYPE=Release BUILD_ENV=linux_x64

    - sudo: required
      env: BUILD_TYPE=Release RUN_TEST=ON NO_DEPLOY=on

script:
  - echo "script"

after_success:
  - echo "after_success"


deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: $BUILD_ENV*.tar.gz
  skip_cleanup: true
  on:
    tags: true
    # condition: $NO_DEPLOY = "" && tag =~ /^(internal-test)/
    condition: |
      NO_DEPLOY IS present AND \
      tag =~ /^(internal-test)/

# notifications:
#  email:
#    recipients:
#    - raozhiming@msn.com
#     on_success: always
#     on_failure: always
