language: c

stages:
  - name: after_success
    if: env(RUN_TEST) IS present

before_install:
  - echo "before_install ***************"

before_script:
  - echo "before_script ***************"

matrix:
  include:
    - os: linux
      dist: xenial
      before_install:
        - echo "job 1 before_install ***************"
      before_script:
        - echo "job 1 before_script ***************"

    - os: linux
      dist: xenial
      script:
        - echo "job 2 script ***************"


script:
  - echo "script ***************"

after_success:
  - echo "after_success"
  
deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: $BUILD_ENV*.tar.gz
  skip_cleanup: true
  on:
    tags: true

# notifications:
#  email:
#    recipients:
#    - raozhiming@msn.com
#     on_success: always
#     on_failure: always
