language: c

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ruby-dev; fi
  - if [[ "$TRAVIS_TAG" != "" ]]; then env:BUILD_VER=Release; else env:BUILD_VER=Debug;fi

matrix:
  include:
    - sudo: required
      env: BUILD_TYPE=Debug
    - sudo: required
      env: BUILD_TYPE=Release
      if: tag IS present

script:
  - gcc main.c && ./a.out && echo "TRAVIS_TAG" $TRAVIS_TAG
  - echo "BUILD_VER " $BUILD_VER


# notifications:
#  email:
#    recipients:
#    - raozhiming@msn.com
#     on_success: always
#     on_failure: always
