language: c

before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ruby-dev; fi
  - if [[ "$TRAVIS_TAG" == "" ]]; then 
      export BUILD_VER=Release; 
      export TEST=OK;
      echo  "BUILD_TYPE" $BUILD_TYPE;
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install ruby-dev; 
      fi
    else 
      export BUILD_VER=Debug;
    fi

before_script:
  - echo "script ***************"
  - pwd

matrix:
  include:
    - os: osx
      env: BUILD_ENV=darwin_x64
      if: BUILD_VER IS present

    - os: osx
      env: BUILD_ENV=darwin_x32
      if: NOT BUILD_VER IS present

    - sudo: required
      env: BUILD_TYPE=Debug $BUILD_VER

    - sudo: required
      env: BUILD_TYPE=Release $BUILD_VER
      
    - sudo: required
      env: BUILD_TYPE=Release
      if: tag IS present

script:
  - if [[ "$BUILD_TYPE" == "Release" ]]; then 
      echo "release ++++++++++++";
    else 
      echo "debug -----------";
    fi
  - pwd
  - gcc main.c && ./a.out && echo "TRAVIS_TAG" $TRAVIS_TAG
  - echo "BUILD_VER " $BUILD_VER


# notifications:
#  email:
#    recipients:
#    - raozhiming@msn.com
#     on_success: always
#     on_failure: always
