language: c

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi

matrix:
  include:
  - sudo: required
    script: gcc main.c && ./a.out
    
  - os: osx
    script: gcc main.c

#notifications:
#  email:
#    recipients:
#    - raozhiming@msn.com
    #on_success: always
    #on_failure: always
