
# language: python
# python: 3.7
sudo: true


matrix:
  include:
  # - env: pythonv=2.7
  - language: android
    dist: trusty
    python: 3.7
    env: pythonv=3.7
    # android:
    #   components:
    #     - tools
    #     - platform-tools
    #     - build-tools-28.0.3
    #     - android-28
    #   licenses:
    #     - 'android-sdk-preview-license-.+'
    #     - 'android-sdk-license-.+'
    #     - 'google-gdk-license-.+'
    addons:
      apt:
        sources:
          - deadsnakes # source required so it finds the package definition below
        packages:
          - python3.7
          - python3-pip

before_install:
  # - sudo apt-get update
  # - sudo apt purge python2.7-minimal
  # - sudo apt-get install python3 python3-pip python3-setuptools
  # - pip3 install --upgrade pip

install:
  # - python3 -m ensurepip --upgrade
  # - python --version
  # - python3 --version
  # - pip3 install --upgrade pip
  # - ls -l /opt/python/
  # - ls -l /usr/bin/p*
  - sudo rm /usr/bin/python
  - sudo ln -s /usr/bin/python3.7 /usr/bin/python
  - python --version
  - python3 -m ensurepip --upgrade
  - pip --version

script:
  - echo "script"

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

